# Generated by Django 3.2 on 2021-04-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_auto_20210425_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='exam_detail',
            new_name='exam_id',
        ),
    ]
